# Localization file (English).
INPUT = 'Enter text: '
SENT = 'Sentences:'
WORDS = 'Words:'
CYLS = 'Syllables:'
ASL = 'Average sentence length (in words):'
ASW = 'Average word length (in syllables):'
FLASH = 'Flash Readability Index:'
EZ = 'The text is very easy to read (for younger students).'
SIMPLE = 'Simple text (for school students).'
HARDER = 'The text is a little hard to read (for university students).'
HARD = 'The text is hard to read (for graduates).'
OBJKV = 'Objectivity: '
KEY = 'Tonality of the text:'
POSITIVE = 'positive.'
NEUTRAL = 'neutral.'
NEGATIVE = 'negative.'
